# Generated by Django 5.2.9 on 2026-01-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='carousel/'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
    ]
