# Generated by Django 5.2.9 on 2026-01-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cart_old_wishlist_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist_old',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist_old',
            name='property',
        ),
        migrations.RemoveField(
            model_name='wishlist_old',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart_old',
        ),
        migrations.DeleteModel(
            name='Wishlist_old',
        ),
    ]
