# Generated by Django 5.2.9 on 2026-01-21 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('users', '0005_alter_user_gender_alter_user_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_variants', to='subscription.subscriptionplanvariant'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='users.user'),
        ),
    ]
