# Generated by Django 5.2.9 on 2026-01-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0007_productvariant_verification_status_and_more'),
        ('property', '0003_userproperty'),
        ('subscription', '0002_remove_subscription_subscription_end_date_and_more'),
        ('users', '0007_remove_wishlist_old_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price snapshot at order time', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.order')),
                ('property_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='property.property')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='business.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_for', models.CharField(choices=[('property', 'Property'), ('subscription', 'Subscription'), ('product', 'Product')], max_length=50)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('purchased_from', models.CharField(blank=True, max_length=150, null=True)),
                ('purchased_type', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('receiver_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=150, null=True)),
                ('property_name', models.CharField(blank=True, max_length=150, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('company_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('receipt', 'Receipt')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='transaction_documents/')),
                ('phone_pe_merchant_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_pe_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_pe_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.order')),
                ('property_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='property.property')),
                ('subscription_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplanvariant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('purchased', 'Purchased')], max_length=20)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
