# Generated by Django 5.2.9 on 2026-01-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businessworkinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.offer'),
        ),
    ]
