# Generated by Django 5.2.9 on 2026-01-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
    ]
