# Generated by Django 5.2.9 on 2026-01-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_product_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
