# Generated by Django 5.2.9 on 2026-01-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
