# Generated by Django 5.2.9 on 2026-01-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_productvariant_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='company_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='distribution_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
