# Generated by Django 5.2.9 on 2026-01-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_productvariant_company_commission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='company_commission',
            new_name='product_commission',
        ),
    ]
