# Generated by Django 5.2.9 on 2026-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_company_commission_productvariant_product_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
