# Generated by Django 5.2.9 on 2026-02-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_productvariant_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
