# Generated by Django 5.2.9 on 2026-01-06 01:21

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAmountSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMIOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_months', models.PositiveIntegerField()),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('looking_to', models.CharField(blank=True, choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=10, null=True)),
                ('property_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('builtup_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('breadth_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing_status', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_open_sides', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_roads', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_balconies', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('road_width_1_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('road_width_2_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('facing', models.CharField(blank=True, choices=[('east', 'East'), ('west', 'West'), ('north', 'North'), ('south', 'South'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=20, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=100, null=True)),
                ('property_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('total_property_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('property_value_without_booking_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('preferred_tenants', models.CharField(blank=True, help_text='e.g., Family, Bachelors, Company Lease', max_length=100, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('available_from', models.CharField(blank=True, max_length=100, null=True)),
                ('property_uniqueness', models.TextField(blank=True, null=True)),
                ('location_advantages', models.TextField(blank=True, null=True)),
                ('other_features', models.TextField(blank=True, null=True)),
                ('listing_days', models.PositiveIntegerField(blank=True, help_text='Number of days the property stays visible', null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_id', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('agent_commission_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('agent_commission_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('company_commission', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('distribution_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remaining_company_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_company_commission_distributed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company_commission_status', models.CharField(default='unpaid', max_length=100)),
                ('agreement_video', models.FileField(blank=True, null=True, upload_to='agreements/videos/')),
                ('agreement_file', models.FileField(blank=True, null=True, upload_to='agreements/files/')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('sold', 'Sold')], default='available', max_length=20)),
                ('approval_status', models.CharField(default='pending', max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('property_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=property.models.property_file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=property.models.property_image_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=property.models.property_video_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='UserEMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
