# Generated by Django 5.2.9 on 2026-01-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_company_commission_productvariant_product_commission'),
        ('property', '0003_userproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business.productvariant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='property.property'),
        ),
    ]
