# Generated by Django 5.2.9 on 2026-01-31 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_company_commission_productvariant_product_commission'),
        ('property', '0004_notification_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business.product'),
        ),
    ]
