# Generated by Django 5.2.9 on 2026-02-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_notification_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremi',
            name='emi_option',
        ),
        migrations.RemoveField(
            model_name='useremi',
            name='property',
        ),
        migrations.RemoveField(
            model_name='useremi',
            name='user',
        ),
        migrations.DeleteModel(
            name='EMIOption',
        ),
        migrations.DeleteModel(
            name='UserEMI',
        ),
    ]
